project_id = "bwqdgorcraiidyqbwlno"

[functions.fetch-environmental-data]
verify_jwt = false

[functions.detect-anomalies]
verify_jwt = false

[functions.predict-conditions]
verify_jwt = false

[functions.analyze-patterns]
verify_jwt = false
